// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.24.4
// source: commonpb/common.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_Bytes
	//	*Value_Str
	//	*Value_Int
	//	*Value_Bool
	//	*Value_List
	//	*Value_Map
	//	*Value_Nil
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_commonpb_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_commonpb_common_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *Value) GetStr() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Value) GetInt() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *Value) GetBool() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *Value) GetList() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Value) GetMap() *MapValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_Map); ok {
			return x.Map
		}
	}
	return nil
}

func (x *Value) GetNil() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_Nil); ok {
			return x.Nil
		}
	}
	return false
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_Bytes struct {
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3,oneof"`
}

type Value_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type Value_Int struct {
	Int int64 `protobuf:"varint,3,opt,name=int,proto3,oneof"`
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,4,opt,name=bool,proto3,oneof"`
}

type Value_List struct {
	List *ListValue `protobuf:"bytes,5,opt,name=list,proto3,oneof"`
}

type Value_Map struct {
	Map *MapValue `protobuf:"bytes,6,opt,name=map,proto3,oneof"`
}

type Value_Nil struct {
	Nil bool `protobuf:"varint,7,opt,name=nil,proto3,oneof"`
}

func (*Value_Bytes) isValue_Kind() {}

func (*Value_Str) isValue_Kind() {}

func (*Value_Int) isValue_Kind() {}

func (*Value_Bool) isValue_Kind() {}

func (*Value_List) isValue_Kind() {}

func (*Value_Map) isValue_Kind() {}

func (*Value_Nil) isValue_Kind() {}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_commonpb_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_commonpb_common_proto_rawDescGZIP(), []int{1}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_commonpb_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_commonpb_common_proto_rawDescGZIP(), []int{2}
}

func (x *MapValue) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Args          [][]byte               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_commonpb_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_commonpb_common_proto_rawDescGZIP(), []int{3}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommandRequest) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Response      *Value                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_commonpb_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_commonpb_common_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResponse) GetResponse() *Value {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_commonpb_common_proto protoreflect.FileDescriptor

const file_commonpb_common_proto_rawDesc = "" +
	"\n" +
	"\x15commonpb/common.proto\x12\bcommonpb\"\xcc\x01\n" +
	"\x05Value\x12\x16\n" +
	"\x05bytes\x18\x01 \x01(\fH\x00R\x05bytes\x12\x12\n" +
	"\x03str\x18\x02 \x01(\tH\x00R\x03str\x12\x12\n" +
	"\x03int\x18\x03 \x01(\x03H\x00R\x03int\x12\x14\n" +
	"\x04bool\x18\x04 \x01(\bH\x00R\x04bool\x12)\n" +
	"\x04list\x18\x05 \x01(\v2\x13.commonpb.ListValueH\x00R\x04list\x12&\n" +
	"\x03map\x18\x06 \x01(\v2\x12.commonpb.MapValueH\x00R\x03map\x12\x12\n" +
	"\x03nil\x18\a \x01(\bH\x00R\x03nilB\x06\n" +
	"\x04kind\"4\n" +
	"\tListValue\x12'\n" +
	"\x06values\x18\x01 \x03(\v2\x0f.commonpb.ValueR\x06values\"\x8e\x01\n" +
	"\bMapValue\x126\n" +
	"\x06values\x18\x01 \x03(\v2\x1e.commonpb.MapValue.ValuesEntryR\x06values\x1aJ\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.commonpb.ValueR\x05value:\x028\x01\"P\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04args\x18\x03 \x03(\fR\x04args\"T\n" +
	"\x0fCommandResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12+\n" +
	"\bresponse\x18\x02 \x01(\v2\x0f.commonpb.ValueR\bresponseB\x1eZ\x1cgokv/proto/commonpb;commonpbb\x06proto3"

var (
	file_commonpb_common_proto_rawDescOnce sync.Once
	file_commonpb_common_proto_rawDescData []byte
)

func file_commonpb_common_proto_rawDescGZIP() []byte {
	file_commonpb_common_proto_rawDescOnce.Do(func() {
		file_commonpb_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commonpb_common_proto_rawDesc), len(file_commonpb_common_proto_rawDesc)))
	})
	return file_commonpb_common_proto_rawDescData
}

var file_commonpb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_commonpb_common_proto_goTypes = []any{
	(*Value)(nil),           // 0: commonpb.Value
	(*ListValue)(nil),       // 1: commonpb.ListValue
	(*MapValue)(nil),        // 2: commonpb.MapValue
	(*CommandRequest)(nil),  // 3: commonpb.CommandRequest
	(*CommandResponse)(nil), // 4: commonpb.CommandResponse
	nil,                     // 5: commonpb.MapValue.ValuesEntry
}
var file_commonpb_common_proto_depIdxs = []int32{
	1, // 0: commonpb.Value.list:type_name -> commonpb.ListValue
	2, // 1: commonpb.Value.map:type_name -> commonpb.MapValue
	0, // 2: commonpb.ListValue.values:type_name -> commonpb.Value
	5, // 3: commonpb.MapValue.values:type_name -> commonpb.MapValue.ValuesEntry
	0, // 4: commonpb.CommandResponse.response:type_name -> commonpb.Value
	0, // 5: commonpb.MapValue.ValuesEntry.value:type_name -> commonpb.Value
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_commonpb_common_proto_init() }
func file_commonpb_common_proto_init() {
	if File_commonpb_common_proto != nil {
		return
	}
	file_commonpb_common_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_Bytes)(nil),
		(*Value_Str)(nil),
		(*Value_Int)(nil),
		(*Value_Bool)(nil),
		(*Value_List)(nil),
		(*Value_Map)(nil),
		(*Value_Nil)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_common_proto_rawDesc), len(file_commonpb_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_common_proto_goTypes,
		DependencyIndexes: file_commonpb_common_proto_depIdxs,
		MessageInfos:      file_commonpb_common_proto_msgTypes,
	}.Build()
	File_commonpb_common_proto = out.File
	file_commonpb_common_proto_goTypes = nil
	file_commonpb_common_proto_depIdxs = nil
}
